### ISSUE TITLE
 It have stopped working since 1.1.0 stable

### ISSUE THREAD

**Issue by lumos401** [IcySnex/WinUI3-Transparent-Mica-Acrylic-Blurred#1]
It works on 1.1.0-preview2 and amazing !

But, it didn't work on 1.1.5.......😇
It seems to have stopped working since 1.1.0 stable.

Are there any way to make it work ?

**Comment by IcySnex** [comment]
Yes this is correct.
The stable version (1.1.0) messed some things up with the transparent window.
You can no longer use ```SetLayeredWindowAttributes(...)``` to set the black orginal background to transparent.
The effect (Mica, Acrylic, Blurred) still gets rendered behind the window but since there is a black window background stuck you cannot see it.

But fortunately there is official support for Mica and Acrylic effects now since the stable version of 1.1.0.
Sadly this removes the simple blurred effect from Windows 7.

You can read the official documentation for the backdrop handlers: https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/system-backdrop-controller.
Or you can also look at one of my other projects where I implemented a few backdrops effects (Mica, Acrylic, "Vibrancy") in a MVVM application (with Dependency Injection): https://github.com/IcyLauncher/Launcher/blob/main/IcyLauncher.Services/BackdropHandler.cs

**Comment by GetGet99** [comment]
Is there a way to get the complete transparent effect? I don't think there is an official support to that yet, right?

**Comment by IcySnex** [comment]
Unfortunately, I think there is currently no option to create a transparent window with WinUi 3 and WindowsAppSDK (> 1.1.0-prev3).
I could be wrong though so you could try to create a new issue on the official [GitHub repo](https://github.com/microsoft/microsoft-ui-xaml) and maybe someone knows a solution.
