### ISSUE TITLE
Doesn't work on Windows 11 23H2

### ISSUE THREAD

**Issue by lovettchris** [IcySnex/WinUI3-Transparent-Mica-Acrylic-Blurred#2]
Using:

		<TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>

And Microsoft.Windows.Sdk 10.0.19041.31

The window is not transparent:

![image](https://github.com/IcySnex/WinUI3-Transparent-Mica-Acrylic-Blurred/assets/18707114/32ee987a-a014-4a91-bc89-7d6d1a1ef3db)

Also tried moving to .net 8, no luck.

**Comment by IcySnex** [comment]
Hello,

please notice that this project is obsolete and no longer working since WndowsAppSDK 1.1-stable (also see README).

Microsoft added official support for Mica and Acrylic backdrop effects since WindowsAppSDK 1.3, which means there is no need for manual Win32 API calls.

For more information see here: https://learn.microsoft.com/windows/apps/windows-app-sdk/system-backdrop-controller

**Comment by lovettchris** [comment]
cool, thanks for the link.
